// This file was auto-generated by ML.NET Model Builder. 

using System;
using VICML.Model;

namespace VICML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Fingerprint = @"",
                Minutia = @"",
                Nn15 = 0F,
                Nn30 = 0F,
                Nn45 = 0F,
                Nn60 = 0F,
                Nn75 = 0F,
                Nn90 = 0F,
                Nn105 = 0F,
                Nn120 = 0F,
                Nn135 = 0F,
                Nn150 = 0F,
                Nn165 = 0F,
                Nn180 = 0F,
                Nn195 = 0F,
                Nn210 = 0F,
                Nn225 = 0F,
                Nn240 = 0F,
                Nn255 = 0F,
                Nn270 = 0F,
                Nn285 = 0F,
                Nn300 = 0F,
                Nn315 = 0F,
                Nn330 = 0F,
                Nn345 = 0F,
                Nn360 = 0F,
                Nn375 = 0F,
                Nn390 = 0F,
                Nn405 = 0F,
                Nn420 = 0F,
                Nn435 = 0F,
                Nn450 = 0F,
                Nn465 = 0F,
                Nn480 = 0F,
                Nn495 = 0F,
                Nn510 = 0F,
                Nn525 = 0F,
                Nn540 = 0F,
                Nn555 = 0F,
                Nn570 = 0F,
                Nn585 = 0F,
                Nn600 = 0F,
                Nn607 = 0F,
                Nn15r = 0F,
                Nn30r = 0F,
                Nn45r = 0F,
                Nn60r = 0F,
                Nn75r = 0F,
                Nn90r = 0F,
                Nn105r = 0F,
                Nn120r = 0F,
                Nn135r = 0F,
                Nn150r = 0F,
                Nn165r = 0F,
                Nn180r = 0F,
                Nn195r = 0F,
                Nn210r = 0F,
                Nn225r = 0F,
                Nn240r = 0F,
                Nn255r = 0F,
                Nn270r = 0F,
                Nn285r = 0F,
                Nn300r = 0F,
                Nn315r = 0F,
                Nn330r = 0F,
                Nn345r = 0F,
                Nn360r = 0F,
                Nn375r = 0F,
                Nn390r = 0F,
                Nn405r = 0F,
                Nn420r = 0F,
                Nn435r = 0F,
                Nn450r = 0F,
                Nn465r = 0F,
                Nn480r = 0F,
                Nn495r = 0F,
                Nn510r = 0F,
                Nn525r = 0F,
                Nn540r = 0F,
                Nn555r = 0F,
                Nn570r = 0F,
                Nn585r = 0F,
                Nn600r = 0F,
                Nn607r = 0F,
                Nn30_nn15 = 0F,
                Nn45_nn30 = 0F,
                Nn60_nn45 = 0F,
                Nn75_nn60 = 0F,
                Nn90_nn75 = 0F,
                Nn105_nn90 = 0F,
                Nn120_nn105 = 0F,
                Nn135_nn120 = 0F,
                Nn150_nn135 = 0F,
                Nn165_nn150 = 0F,
                Nn180_nn165 = 0F,
                Nn195_nn180 = 0F,
                Nn210_nn195 = 0F,
                Nn225_nn210 = 0F,
                Nn240_nn225 = 0F,
                Nn255_nn240 = 0F,
                Nn270_nn255 = 0F,
                Nn285_nn270 = 0F,
                Nn300_nn285 = 0F,
                Nn315_nn300 = 0F,
                Nn330_nn315 = 0F,
                Nn345_nn330 = 0F,
                Nn360_nn345 = 0F,
                Nn375_nn360 = 0F,
                Nn390_nn375 = 0F,
                Nn405_nn390 = 0F,
                Nn420_nn405 = 0F,
                Nn435_nn420 = 0F,
                Nn450_nn435 = 0F,
                Nn465_nn450 = 0F,
                Nn480_nn465 = 0F,
                Nn495_nn480 = 0F,
                Nn510_nn495 = 0F,
                Nn525_nn510 = 0F,
                Nn540_nn525 = 0F,
                Nn555_nn540 = 0F,
                Nn570_nn555 = 0F,
                Nn585_nn570 = 0F,
                Nn600_nn585 = 0F,
                Nn607_nn600 = 0F,
                Nn30r_nn15r = 0F,
                Nn45r_nn30r = 0F,
                Nn60r_nn45r = 0F,
                Nn75r_nn60r = 0F,
                Nn90r_nn75r = 0F,
                Nn105r_nn90r = 0F,
                Nn120r_nn105r = 0F,
                Nn135r_nn120r = 0F,
                Nn150r_nn135r = 0F,
                Nn165r_nn150r = 0F,
                Nn180r_nn165r = 0F,
                Nn195r_nn180r = 0F,
                Nn210r_nn195r = 0F,
                Nn225r_nn210r = 0F,
                Nn240r_nn225r = 0F,
                Nn255r_nn240r = 0F,
                Nn270r_nn255r = 0F,
                Nn285r_nn270r = 0F,
                Nn300r_nn285r = 0F,
                Nn315r_nn300r = 0F,
                Nn330r_nn315r = 0F,
                Nn345r_nn330r = 0F,
                Nn360r_nn345r = 0F,
                Nn375r_nn360r = 0F,
                Nn390r_nn375r = 0F,
                Nn405r_nn390r = 0F,
                Nn420r_nn405r = 0F,
                Nn435r_nn420r = 0F,
                Nn450r_nn435r = 0F,
                Nn465r_nn450r = 0F,
                Nn480r_nn465r = 0F,
                Nn495r_nn480r = 0F,
                Nn510r_nn495r = 0F,
                Nn525r_nn510r = 0F,
                Nn540r_nn525r = 0F,
                Nn555r_nn540r = 0F,
                Nn570r_nn555r = 0F,
                Nn585r_nn570r = 0F,
                Nn600r_nn585r = 0F,
                Nn607r_nn600r = 0F,
                D1 = 0F,
                D2 = 0F,
                D3 = 0F,
                D4 = 0F,
                D5 = 0F,
                D6 = 0F,
                D7 = 0F,
                D8 = 0F,
                D9 = 0F,
                D10 = 0F,
                D11 = 0F,
                D12 = 0F,
                Df = 0F,
                D1r = 0F,
                D2r = 0F,
                D3r = 0F,
                D4r = 0F,
                D5r = 0F,
                D6r = 0F,
                D7r = 0F,
                D8r = 0F,
                D9r = 0F,
                D10r = 0F,
                D11r = 0F,
                D12r = 0F,
                Dfr = 0F,
                D2_d1 = 0F,
                D3_d2 = 0F,
                D4_d3 = 0F,
                D5_d4 = 0F,
                D6_d5 = 0F,
                D7_d6 = 0F,
                D8_d7 = 0F,
                D9_d8 = 0F,
                D10_d9 = 0F,
                D11_d10 = 0F,
                D12_d11 = 0F,
                Df_d12 = 0F,
                D2r_d1r = 0F,
                D3r_d2r = 0F,
                D4r_d3r = 0F,
                D5r_d4r = 0F,
                D6r_d5r = 0F,
                D7r_d6r = 0F,
                D8r_d7r = 0F,
                D9r_d8r = 0F,
                D10r_d9r = 0F,
                D11r_d10r = 0F,
                D12r_d11r = 0F,
                Dfr_d12r = 0F,
                Alpha1 = 0F,
                Alpha2 = 0F,
                Alpha3 = 0F,
                Alpha4 = 0F,
                Alpha5 = 0F,
                Alpha6 = 0F,
                Alpha7 = 0F,
                Alpha8 = 0F,
                Alpha9 = 0F,
                Alpha10 = 0F,
                Alpha11 = 0F,
                Alpha12 = 0F,
                Alphaf = 0F,
                Alphan1 = 0F,
                Alphan2 = 0F,
                Alphan3 = 0F,
                Alphan4 = 0F,
                Alphan5 = 0F,
                Alphan6 = 0F,
                Alphan7 = 0F,
                Alphan8 = 0F,
                Alphan9 = 0F,
                Alphan10 = 0F,
                Alphan11 = 0F,
                Alphan12 = 0F,
                Alphanf = 0F,
                Beta1 = 0F,
                Beta2 = 0F,
                Beta3 = 0F,
                Beta4 = 0F,
                Beta5 = 0F,
                Beta6 = 0F,
                Beta7 = 0F,
                Beta8 = 0F,
                Beta9 = 0F,
                Beta10 = 0F,
                Beta11 = 0F,
                Beta12 = 0F,
                Betaf = 0F,
                Alpha1_beta1 = 0F,
                Alpha2_beta2 = 0F,
                Alpha3_beta3 = 0F,
                Alpha4_beta4 = 0F,
                Alpha5_beta5 = 0F,
                Alpha6_beta6 = 0F,
                Alpha7_beta7 = 0F,
                Alpha8_beta8 = 0F,
                Alpha9_beta9 = 0F,
                Alpha10_beta10 = 0F,
                Alpha11_beta11 = 0F,
                Alpha12_beta12 = 0F,
                Alphaf_betaf = 0F,
                Type = @"",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");
            Console.WriteLine($"Fingerprint: {sampleData.Fingerprint}");
            Console.WriteLine($"Minutia: {sampleData.Minutia}");
            Console.WriteLine($"Nn15: {sampleData.Nn15}");
            Console.WriteLine($"Nn30: {sampleData.Nn30}");
            Console.WriteLine($"Nn45: {sampleData.Nn45}");
            Console.WriteLine($"Nn60: {sampleData.Nn60}");
            Console.WriteLine($"Nn75: {sampleData.Nn75}");
            Console.WriteLine($"Nn90: {sampleData.Nn90}");
            Console.WriteLine($"Nn105: {sampleData.Nn105}");
            Console.WriteLine($"Nn120: {sampleData.Nn120}");
            Console.WriteLine($"Nn135: {sampleData.Nn135}");
            Console.WriteLine($"Nn150: {sampleData.Nn150}");
            Console.WriteLine($"Nn165: {sampleData.Nn165}");
            Console.WriteLine($"Nn180: {sampleData.Nn180}");
            Console.WriteLine($"Nn195: {sampleData.Nn195}");
            Console.WriteLine($"Nn210: {sampleData.Nn210}");
            Console.WriteLine($"Nn225: {sampleData.Nn225}");
            Console.WriteLine($"Nn240: {sampleData.Nn240}");
            Console.WriteLine($"Nn255: {sampleData.Nn255}");
            Console.WriteLine($"Nn270: {sampleData.Nn270}");
            Console.WriteLine($"Nn285: {sampleData.Nn285}");
            Console.WriteLine($"Nn300: {sampleData.Nn300}");
            Console.WriteLine($"Nn315: {sampleData.Nn315}");
            Console.WriteLine($"Nn330: {sampleData.Nn330}");
            Console.WriteLine($"Nn345: {sampleData.Nn345}");
            Console.WriteLine($"Nn360: {sampleData.Nn360}");
            Console.WriteLine($"Nn375: {sampleData.Nn375}");
            Console.WriteLine($"Nn390: {sampleData.Nn390}");
            Console.WriteLine($"Nn405: {sampleData.Nn405}");
            Console.WriteLine($"Nn420: {sampleData.Nn420}");
            Console.WriteLine($"Nn435: {sampleData.Nn435}");
            Console.WriteLine($"Nn450: {sampleData.Nn450}");
            Console.WriteLine($"Nn465: {sampleData.Nn465}");
            Console.WriteLine($"Nn480: {sampleData.Nn480}");
            Console.WriteLine($"Nn495: {sampleData.Nn495}");
            Console.WriteLine($"Nn510: {sampleData.Nn510}");
            Console.WriteLine($"Nn525: {sampleData.Nn525}");
            Console.WriteLine($"Nn540: {sampleData.Nn540}");
            Console.WriteLine($"Nn555: {sampleData.Nn555}");
            Console.WriteLine($"Nn570: {sampleData.Nn570}");
            Console.WriteLine($"Nn585: {sampleData.Nn585}");
            Console.WriteLine($"Nn600: {sampleData.Nn600}");
            Console.WriteLine($"Nn607: {sampleData.Nn607}");
            Console.WriteLine($"Nn15r: {sampleData.Nn15r}");
            Console.WriteLine($"Nn30r: {sampleData.Nn30r}");
            Console.WriteLine($"Nn45r: {sampleData.Nn45r}");
            Console.WriteLine($"Nn60r: {sampleData.Nn60r}");
            Console.WriteLine($"Nn75r: {sampleData.Nn75r}");
            Console.WriteLine($"Nn90r: {sampleData.Nn90r}");
            Console.WriteLine($"Nn105r: {sampleData.Nn105r}");
            Console.WriteLine($"Nn120r: {sampleData.Nn120r}");
            Console.WriteLine($"Nn135r: {sampleData.Nn135r}");
            Console.WriteLine($"Nn150r: {sampleData.Nn150r}");
            Console.WriteLine($"Nn165r: {sampleData.Nn165r}");
            Console.WriteLine($"Nn180r: {sampleData.Nn180r}");
            Console.WriteLine($"Nn195r: {sampleData.Nn195r}");
            Console.WriteLine($"Nn210r: {sampleData.Nn210r}");
            Console.WriteLine($"Nn225r: {sampleData.Nn225r}");
            Console.WriteLine($"Nn240r: {sampleData.Nn240r}");
            Console.WriteLine($"Nn255r: {sampleData.Nn255r}");
            Console.WriteLine($"Nn270r: {sampleData.Nn270r}");
            Console.WriteLine($"Nn285r: {sampleData.Nn285r}");
            Console.WriteLine($"Nn300r: {sampleData.Nn300r}");
            Console.WriteLine($"Nn315r: {sampleData.Nn315r}");
            Console.WriteLine($"Nn330r: {sampleData.Nn330r}");
            Console.WriteLine($"Nn345r: {sampleData.Nn345r}");
            Console.WriteLine($"Nn360r: {sampleData.Nn360r}");
            Console.WriteLine($"Nn375r: {sampleData.Nn375r}");
            Console.WriteLine($"Nn390r: {sampleData.Nn390r}");
            Console.WriteLine($"Nn405r: {sampleData.Nn405r}");
            Console.WriteLine($"Nn420r: {sampleData.Nn420r}");
            Console.WriteLine($"Nn435r: {sampleData.Nn435r}");
            Console.WriteLine($"Nn450r: {sampleData.Nn450r}");
            Console.WriteLine($"Nn465r: {sampleData.Nn465r}");
            Console.WriteLine($"Nn480r: {sampleData.Nn480r}");
            Console.WriteLine($"Nn495r: {sampleData.Nn495r}");
            Console.WriteLine($"Nn510r: {sampleData.Nn510r}");
            Console.WriteLine($"Nn525r: {sampleData.Nn525r}");
            Console.WriteLine($"Nn540r: {sampleData.Nn540r}");
            Console.WriteLine($"Nn555r: {sampleData.Nn555r}");
            Console.WriteLine($"Nn570r: {sampleData.Nn570r}");
            Console.WriteLine($"Nn585r: {sampleData.Nn585r}");
            Console.WriteLine($"Nn600r: {sampleData.Nn600r}");
            Console.WriteLine($"Nn607r: {sampleData.Nn607r}");
            Console.WriteLine($"Nn30_nn15: {sampleData.Nn30_nn15}");
            Console.WriteLine($"Nn45_nn30: {sampleData.Nn45_nn30}");
            Console.WriteLine($"Nn60_nn45: {sampleData.Nn60_nn45}");
            Console.WriteLine($"Nn75_nn60: {sampleData.Nn75_nn60}");
            Console.WriteLine($"Nn90_nn75: {sampleData.Nn90_nn75}");
            Console.WriteLine($"Nn105_nn90: {sampleData.Nn105_nn90}");
            Console.WriteLine($"Nn120_nn105: {sampleData.Nn120_nn105}");
            Console.WriteLine($"Nn135_nn120: {sampleData.Nn135_nn120}");
            Console.WriteLine($"Nn150_nn135: {sampleData.Nn150_nn135}");
            Console.WriteLine($"Nn165_nn150: {sampleData.Nn165_nn150}");
            Console.WriteLine($"Nn180_nn165: {sampleData.Nn180_nn165}");
            Console.WriteLine($"Nn195_nn180: {sampleData.Nn195_nn180}");
            Console.WriteLine($"Nn210_nn195: {sampleData.Nn210_nn195}");
            Console.WriteLine($"Nn225_nn210: {sampleData.Nn225_nn210}");
            Console.WriteLine($"Nn240_nn225: {sampleData.Nn240_nn225}");
            Console.WriteLine($"Nn255_nn240: {sampleData.Nn255_nn240}");
            Console.WriteLine($"Nn270_nn255: {sampleData.Nn270_nn255}");
            Console.WriteLine($"Nn285_nn270: {sampleData.Nn285_nn270}");
            Console.WriteLine($"Nn300_nn285: {sampleData.Nn300_nn285}");
            Console.WriteLine($"Nn315_nn300: {sampleData.Nn315_nn300}");
            Console.WriteLine($"Nn330_nn315: {sampleData.Nn330_nn315}");
            Console.WriteLine($"Nn345_nn330: {sampleData.Nn345_nn330}");
            Console.WriteLine($"Nn360_nn345: {sampleData.Nn360_nn345}");
            Console.WriteLine($"Nn375_nn360: {sampleData.Nn375_nn360}");
            Console.WriteLine($"Nn390_nn375: {sampleData.Nn390_nn375}");
            Console.WriteLine($"Nn405_nn390: {sampleData.Nn405_nn390}");
            Console.WriteLine($"Nn420_nn405: {sampleData.Nn420_nn405}");
            Console.WriteLine($"Nn435_nn420: {sampleData.Nn435_nn420}");
            Console.WriteLine($"Nn450_nn435: {sampleData.Nn450_nn435}");
            Console.WriteLine($"Nn465_nn450: {sampleData.Nn465_nn450}");
            Console.WriteLine($"Nn480_nn465: {sampleData.Nn480_nn465}");
            Console.WriteLine($"Nn495_nn480: {sampleData.Nn495_nn480}");
            Console.WriteLine($"Nn510_nn495: {sampleData.Nn510_nn495}");
            Console.WriteLine($"Nn525_nn510: {sampleData.Nn525_nn510}");
            Console.WriteLine($"Nn540_nn525: {sampleData.Nn540_nn525}");
            Console.WriteLine($"Nn555_nn540: {sampleData.Nn555_nn540}");
            Console.WriteLine($"Nn570_nn555: {sampleData.Nn570_nn555}");
            Console.WriteLine($"Nn585_nn570: {sampleData.Nn585_nn570}");
            Console.WriteLine($"Nn600_nn585: {sampleData.Nn600_nn585}");
            Console.WriteLine($"Nn607_nn600: {sampleData.Nn607_nn600}");
            Console.WriteLine($"Nn30r_nn15r: {sampleData.Nn30r_nn15r}");
            Console.WriteLine($"Nn45r_nn30r: {sampleData.Nn45r_nn30r}");
            Console.WriteLine($"Nn60r_nn45r: {sampleData.Nn60r_nn45r}");
            Console.WriteLine($"Nn75r_nn60r: {sampleData.Nn75r_nn60r}");
            Console.WriteLine($"Nn90r_nn75r: {sampleData.Nn90r_nn75r}");
            Console.WriteLine($"Nn105r_nn90r: {sampleData.Nn105r_nn90r}");
            Console.WriteLine($"Nn120r_nn105r: {sampleData.Nn120r_nn105r}");
            Console.WriteLine($"Nn135r_nn120r: {sampleData.Nn135r_nn120r}");
            Console.WriteLine($"Nn150r_nn135r: {sampleData.Nn150r_nn135r}");
            Console.WriteLine($"Nn165r_nn150r: {sampleData.Nn165r_nn150r}");
            Console.WriteLine($"Nn180r_nn165r: {sampleData.Nn180r_nn165r}");
            Console.WriteLine($"Nn195r_nn180r: {sampleData.Nn195r_nn180r}");
            Console.WriteLine($"Nn210r_nn195r: {sampleData.Nn210r_nn195r}");
            Console.WriteLine($"Nn225r_nn210r: {sampleData.Nn225r_nn210r}");
            Console.WriteLine($"Nn240r_nn225r: {sampleData.Nn240r_nn225r}");
            Console.WriteLine($"Nn255r_nn240r: {sampleData.Nn255r_nn240r}");
            Console.WriteLine($"Nn270r_nn255r: {sampleData.Nn270r_nn255r}");
            Console.WriteLine($"Nn285r_nn270r: {sampleData.Nn285r_nn270r}");
            Console.WriteLine($"Nn300r_nn285r: {sampleData.Nn300r_nn285r}");
            Console.WriteLine($"Nn315r_nn300r: {sampleData.Nn315r_nn300r}");
            Console.WriteLine($"Nn330r_nn315r: {sampleData.Nn330r_nn315r}");
            Console.WriteLine($"Nn345r_nn330r: {sampleData.Nn345r_nn330r}");
            Console.WriteLine($"Nn360r_nn345r: {sampleData.Nn360r_nn345r}");
            Console.WriteLine($"Nn375r_nn360r: {sampleData.Nn375r_nn360r}");
            Console.WriteLine($"Nn390r_nn375r: {sampleData.Nn390r_nn375r}");
            Console.WriteLine($"Nn405r_nn390r: {sampleData.Nn405r_nn390r}");
            Console.WriteLine($"Nn420r_nn405r: {sampleData.Nn420r_nn405r}");
            Console.WriteLine($"Nn435r_nn420r: {sampleData.Nn435r_nn420r}");
            Console.WriteLine($"Nn450r_nn435r: {sampleData.Nn450r_nn435r}");
            Console.WriteLine($"Nn465r_nn450r: {sampleData.Nn465r_nn450r}");
            Console.WriteLine($"Nn480r_nn465r: {sampleData.Nn480r_nn465r}");
            Console.WriteLine($"Nn495r_nn480r: {sampleData.Nn495r_nn480r}");
            Console.WriteLine($"Nn510r_nn495r: {sampleData.Nn510r_nn495r}");
            Console.WriteLine($"Nn525r_nn510r: {sampleData.Nn525r_nn510r}");
            Console.WriteLine($"Nn540r_nn525r: {sampleData.Nn540r_nn525r}");
            Console.WriteLine($"Nn555r_nn540r: {sampleData.Nn555r_nn540r}");
            Console.WriteLine($"Nn570r_nn555r: {sampleData.Nn570r_nn555r}");
            Console.WriteLine($"Nn585r_nn570r: {sampleData.Nn585r_nn570r}");
            Console.WriteLine($"Nn600r_nn585r: {sampleData.Nn600r_nn585r}");
            Console.WriteLine($"Nn607r_nn600r: {sampleData.Nn607r_nn600r}");
            Console.WriteLine($"D1: {sampleData.D1}");
            Console.WriteLine($"D2: {sampleData.D2}");
            Console.WriteLine($"D3: {sampleData.D3}");
            Console.WriteLine($"D4: {sampleData.D4}");
            Console.WriteLine($"D5: {sampleData.D5}");
            Console.WriteLine($"D6: {sampleData.D6}");
            Console.WriteLine($"D7: {sampleData.D7}");
            Console.WriteLine($"D8: {sampleData.D8}");
            Console.WriteLine($"D9: {sampleData.D9}");
            Console.WriteLine($"D10: {sampleData.D10}");
            Console.WriteLine($"D11: {sampleData.D11}");
            Console.WriteLine($"D12: {sampleData.D12}");
            Console.WriteLine($"Df: {sampleData.Df}");
            Console.WriteLine($"D1r: {sampleData.D1r}");
            Console.WriteLine($"D2r: {sampleData.D2r}");
            Console.WriteLine($"D3r: {sampleData.D3r}");
            Console.WriteLine($"D4r: {sampleData.D4r}");
            Console.WriteLine($"D5r: {sampleData.D5r}");
            Console.WriteLine($"D6r: {sampleData.D6r}");
            Console.WriteLine($"D7r: {sampleData.D7r}");
            Console.WriteLine($"D8r: {sampleData.D8r}");
            Console.WriteLine($"D9r: {sampleData.D9r}");
            Console.WriteLine($"D10r: {sampleData.D10r}");
            Console.WriteLine($"D11r: {sampleData.D11r}");
            Console.WriteLine($"D12r: {sampleData.D12r}");
            Console.WriteLine($"Dfr: {sampleData.Dfr}");
            Console.WriteLine($"D2_d1: {sampleData.D2_d1}");
            Console.WriteLine($"D3_d2: {sampleData.D3_d2}");
            Console.WriteLine($"D4_d3: {sampleData.D4_d3}");
            Console.WriteLine($"D5_d4: {sampleData.D5_d4}");
            Console.WriteLine($"D6_d5: {sampleData.D6_d5}");
            Console.WriteLine($"D7_d6: {sampleData.D7_d6}");
            Console.WriteLine($"D8_d7: {sampleData.D8_d7}");
            Console.WriteLine($"D9_d8: {sampleData.D9_d8}");
            Console.WriteLine($"D10_d9: {sampleData.D10_d9}");
            Console.WriteLine($"D11_d10: {sampleData.D11_d10}");
            Console.WriteLine($"D12_d11: {sampleData.D12_d11}");
            Console.WriteLine($"Df_d12: {sampleData.Df_d12}");
            Console.WriteLine($"D2r_d1r: {sampleData.D2r_d1r}");
            Console.WriteLine($"D3r_d2r: {sampleData.D3r_d2r}");
            Console.WriteLine($"D4r_d3r: {sampleData.D4r_d3r}");
            Console.WriteLine($"D5r_d4r: {sampleData.D5r_d4r}");
            Console.WriteLine($"D6r_d5r: {sampleData.D6r_d5r}");
            Console.WriteLine($"D7r_d6r: {sampleData.D7r_d6r}");
            Console.WriteLine($"D8r_d7r: {sampleData.D8r_d7r}");
            Console.WriteLine($"D9r_d8r: {sampleData.D9r_d8r}");
            Console.WriteLine($"D10r_d9r: {sampleData.D10r_d9r}");
            Console.WriteLine($"D11r_d10r: {sampleData.D11r_d10r}");
            Console.WriteLine($"D12r_d11r: {sampleData.D12r_d11r}");
            Console.WriteLine($"Dfr_d12r: {sampleData.Dfr_d12r}");
            Console.WriteLine($"Alpha1: {sampleData.Alpha1}");
            Console.WriteLine($"Alpha2: {sampleData.Alpha2}");
            Console.WriteLine($"Alpha3: {sampleData.Alpha3}");
            Console.WriteLine($"Alpha4: {sampleData.Alpha4}");
            Console.WriteLine($"Alpha5: {sampleData.Alpha5}");
            Console.WriteLine($"Alpha6: {sampleData.Alpha6}");
            Console.WriteLine($"Alpha7: {sampleData.Alpha7}");
            Console.WriteLine($"Alpha8: {sampleData.Alpha8}");
            Console.WriteLine($"Alpha9: {sampleData.Alpha9}");
            Console.WriteLine($"Alpha10: {sampleData.Alpha10}");
            Console.WriteLine($"Alpha11: {sampleData.Alpha11}");
            Console.WriteLine($"Alpha12: {sampleData.Alpha12}");
            Console.WriteLine($"Alphaf: {sampleData.Alphaf}");
            Console.WriteLine($"Alphan1: {sampleData.Alphan1}");
            Console.WriteLine($"Alphan2: {sampleData.Alphan2}");
            Console.WriteLine($"Alphan3: {sampleData.Alphan3}");
            Console.WriteLine($"Alphan4: {sampleData.Alphan4}");
            Console.WriteLine($"Alphan5: {sampleData.Alphan5}");
            Console.WriteLine($"Alphan6: {sampleData.Alphan6}");
            Console.WriteLine($"Alphan7: {sampleData.Alphan7}");
            Console.WriteLine($"Alphan8: {sampleData.Alphan8}");
            Console.WriteLine($"Alphan9: {sampleData.Alphan9}");
            Console.WriteLine($"Alphan10: {sampleData.Alphan10}");
            Console.WriteLine($"Alphan11: {sampleData.Alphan11}");
            Console.WriteLine($"Alphan12: {sampleData.Alphan12}");
            Console.WriteLine($"Alphanf: {sampleData.Alphanf}");
            Console.WriteLine($"Beta1: {sampleData.Beta1}");
            Console.WriteLine($"Beta2: {sampleData.Beta2}");
            Console.WriteLine($"Beta3: {sampleData.Beta3}");
            Console.WriteLine($"Beta4: {sampleData.Beta4}");
            Console.WriteLine($"Beta5: {sampleData.Beta5}");
            Console.WriteLine($"Beta6: {sampleData.Beta6}");
            Console.WriteLine($"Beta7: {sampleData.Beta7}");
            Console.WriteLine($"Beta8: {sampleData.Beta8}");
            Console.WriteLine($"Beta9: {sampleData.Beta9}");
            Console.WriteLine($"Beta10: {sampleData.Beta10}");
            Console.WriteLine($"Beta11: {sampleData.Beta11}");
            Console.WriteLine($"Beta12: {sampleData.Beta12}");
            Console.WriteLine($"Betaf: {sampleData.Betaf}");
            Console.WriteLine($"Alpha1_beta1: {sampleData.Alpha1_beta1}");
            Console.WriteLine($"Alpha2_beta2: {sampleData.Alpha2_beta2}");
            Console.WriteLine($"Alpha3_beta3: {sampleData.Alpha3_beta3}");
            Console.WriteLine($"Alpha4_beta4: {sampleData.Alpha4_beta4}");
            Console.WriteLine($"Alpha5_beta5: {sampleData.Alpha5_beta5}");
            Console.WriteLine($"Alpha6_beta6: {sampleData.Alpha6_beta6}");
            Console.WriteLine($"Alpha7_beta7: {sampleData.Alpha7_beta7}");
            Console.WriteLine($"Alpha8_beta8: {sampleData.Alpha8_beta8}");
            Console.WriteLine($"Alpha9_beta9: {sampleData.Alpha9_beta9}");
            Console.WriteLine($"Alpha10_beta10: {sampleData.Alpha10_beta10}");
            Console.WriteLine($"Alpha11_beta11: {sampleData.Alpha11_beta11}");
            Console.WriteLine($"Alpha12_beta12: {sampleData.Alpha12_beta12}");
            Console.WriteLine($"Alphaf_betaf: {sampleData.Alphaf_betaf}");
            Console.WriteLine($"Type: {sampleData.Type}");
            Console.WriteLine($"\n\nPredicted Label value {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
